In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import acf
from statsmodels.tsa.stattools import adfuller
import warnings
# para ocultar adventencias
warnings.filterwarnings('ignore')

In [2]:
sismosdf = pd.read_csv('SSNMX_catalogo_20120101_20151231.csv', skiprows=4)
sismosdf.head()

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,2012-01-01,01:47:52,3.5,14.4848,-92.8970,15.0,"83 km al SUROESTE de TAPACHULA, CHIS",2012-01-01,07:47:52,revisado
1,2012-01-01,02:11:48,3.6,18.1745,-100.4220,58.9,"21 km al SUROESTE de ARCELIA, GRO",2012-01-01,08:11:48,revisado
2,2012-01-01,02:46:48,3.7,15.9422,-95.7073,63.9,"50 km al NORESTE de CRUCECITA, OAX",2012-01-01,08:46:48,revisado
3,2012-01-01,03:49:15,3.2,14.6387,-92.7647,68.3,"62 km al SUROESTE de TAPACHULA, CHIS",2012-01-01,09:49:15,revisado
4,2012-01-01,04:24:00,4.0,17.0940,-101.2550,13.0,"49 km al SUR de PETATLAN, GRO",2012-01-01,10:24:00,revisado

In [3]:
sismosdf.info()
#cambiar magnitud a numérica
sismosdf['Magnitud'] = pd.to_numeric(sismosdf['Magnitud'], errors='coerce')

<class 'pandas.DataFrame'>
RangeIndex: 29166 entries, 0 to 29165
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fecha                       29166 non-null  str
 1   Hora                        29159 non-null  str
 2   Magnitud                    29159 non-null  str
 3   Latitud                     29159 non-null  float64
 4   Longitud                    29159 non-null  float64
 5   Profundidad                 29159 non-null  float64
 6   Referencia de localizacion  29159 non-null  str
 7   Fecha UTC                   29159 non-null  str
 8   Hora UTC                    29159 non-null  str
 9   Estatus                     29159 non-null  str
dtypes: float64(3), str(7)
memory usage: 2.2 MB

In [4]:
sismosdf['Fecha'] = pd.to_datetime(sismosdf['Fecha'], errors='coerce')
sismosdf = sismosdf.dropna(subset=['Fecha'])

promedio_magnitud = (
    sismosdf
    .groupby('Fecha')['Magnitud']
    .mean()
    .reset_index()
)

promedio_magnitud.head()

       Fecha  Magnitud
0 2012-01-01  3.693750
1 2012-01-02  3.744444
2 2012-01-03  3.828571
3 2012-01-04  3.685714
4 2012-01-05  3.610000

In [5]:
# Slicing los primero dos años
promedio_magnitud_2014_2015 = promedio_magnitud[
    (promedio_magnitud['Fecha'] >= '2014-01-01') &
    (promedio_magnitud['Fecha'] <= '2015-12-31')
]

In [6]:
promedio_magnitud_2014_2015.head(10)

         Fecha  Magnitud
731 2014-01-01  3.853333
732 2014-01-02  3.981250
733 2014-01-03  3.709091
734 2014-01-04  3.616667
735 2014-01-05  3.726087
736 2014-01-06  3.606667
737 2014-01-07  3.646154
738 2014-01-08  3.568750
739 2014-01-09  3.656250
740 2014-01-10  3.521429

In [7]:
promedio_magnitud_2014_2015.head()

         Fecha  Magnitud
731 2014-01-01  3.853333
732 2014-01-02  3.981250
733 2014-01-03  3.709091
734 2014-01-04  3.616667
735 2014-01-05  3.726087